# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * 0"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.8
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: GlynLeine
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          repositories_affiliations: owner,organization_member,collaborator
          config_timezone: Europe/Amsterdam
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: user
          plugin_habits: yes
          plugin_languages: no
          plugin_lines: yes
          plugin_repositories: yes
          plugin_repositories_affiliations: collaborator
          plugin_repositories_featured: rythe-interactive/Rythe-Engine
          plugin_traffic: yes
